# Generated by Django 4.1.4 on 2023-01-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_img', models.ImageField(blank=True, default='', upload_to='gameimages/')),
                ('item_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=1000)),
                ('last_level', models.IntegerField()),
                ('placement', models.IntegerField()),
                ('last_round', models.IntegerField()),
                ('play_time', models.FloatField()),
                ('gold_left', models.IntegerField()),
                ('total_damage_to_players', models.IntegerField()),
                ('augments', models.JSONField()),
                ('traits', models.JSONField()),
                ('champions', models.JSONField()),
                ('tiers', models.JSONField()),
                ('items', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(max_length=200)),
                ('trait_img', models.ImageField(blank=True, default='', upload_to='gameimages/')),
                ('trait_champions_name', models.CharField(max_length=200)),
                ('trait_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UpperItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_img', models.ImageField(blank=True, default='', upload_to='gameimages/')),
                ('item_info', models.CharField(max_length=1000)),
                ('base_items', models.ManyToManyField(related_name='base_item', to='riotanalysisapp.baseitem')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_name', models.CharField(max_length=200)),
                ('champion_img', models.ImageField(blank=True, default='', upload_to='gameimages/')),
                ('champion_info', models.CharField(max_length=1000)),
                ('champion_cost', models.IntegerField()),
                ('traits', models.ManyToManyField(related_name='trait', to='riotanalysisapp.trait')),
            ],
        ),
    ]
