# Generated by Django 4.1.4 on 2023-01-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotanalysisapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='champions',
            new_name='units',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='items',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='tiers',
        ),
        migrations.AddField(
            model_name='matchdata',
            name='match_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='puuid',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
