# Generated by Django 4.1.4 on 2023-01-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotanalysisapp', '0002_rename_champions_matchdata_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='game_type',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='set_number',
            field=models.IntegerField(default=0),
        ),
    ]
